version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
     - ./monitor:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
    restart: always
    depends_on:
     - node-exporter
       
####node-exporter####
  node-exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
    restart: always
#    network_mode: host

####grafana####
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    restart: always
    command: "GF_SECURITY_ADMIN_PASSWORD=secret"
    depends_on:
      - prometheus
####snmp_exporter####
  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
     - ./snmp:/etc/snmp_exporter
    ports:
      - "9116:9116"
    restart: always
    depends_on:
       - prometheus

