# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: "node"
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: "grafana"
    static_configs:
      - targets: ['grafana:3000']
  - job_name: "snmp-exporter"
    static_configs:
      - targets: ['snmp-exporter:9116']

####################snmp##############################

  - job_name: 'snmp'
    scrape_interval: 2s
    scrape_timeout: 2s
    static_configs:
      - targets:
        - 10.1.1.21 # HP 24 port switch
#        - 10.1.1.22 # HP 8 port switch
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # The SNMP exporter's real hostname:port.

